### ISSUE TITLE
TypeScript error: Class constructor Person cannot be invoked without 'new'

### ISSUE THREAD

**Issue by kristianmandrup** [darkobits/class-decorators#1]
Trying to use your library from Typescript 2.6.x

Any idea what could be the issue here?

```bash
 FAIL  test/_playbox/superpowers.test.ts
  ✕ superpowers (4ms)

  ● superpowers

    TypeError: Class constructor Person cannot be invoked without 'new'
      
      at new Person (node_modules/@darkobits/class-decorator/dist/class-decorator.js:85:22)
      at Object.<anonymous>.test (test/_playbox/superpowers.test.ts:40:17)
```

```js
import classDecorator from '@darkobits/class-decorator';

function addSuperpowers(...powers) {
  return classDecorator({
    onConstruct() {
      powers.forEach(power => {
        this[power] = true;
      });
    },
    prototype: {
      hasSuperpower(power) {
        return this[power];
      }
    }
  });
}

@addSuperpowers('strength', 'speed', 'flight')
class Person {
  name: string
  constructor(name) {
    this.name = name;
  }

  getName() {
    return this.name;
  }
}

test('superpowers', () => {
  const bob = new Person('Bob');
  expect(bob.strength).toBeTruthy()
})
```

My `tsconfig.json` set with target `es6`. 

```json
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "lib": [
      "es6",
      "dom"
    ],
    "outDir": "./dist",
    "allowJs": true,
    "types": [
      "node",
      "jest",
      "jest-jquery-matchers"
    ]
  },
  "exclude": [
    "node_modules"
  ]
}
```

And `jest.config.json` 

```json
  "transform": {
    "^.+\\.(js|jsx)$": "<rootDir>/node_modules/babel-jest",
    "^.+\\.(ts|js|jsx|tsx)$": "<rootDir>/preprocessor.js"
  },
  "transformIgnorePatterns": [
    "<rootDir>/node_modules/(?!@tecla5)",
  ],
```

PS: I had the exact same problem with this example:

```js
function logClass(target: any) {

  // save a reference to the original constructor
  var original = target;

  // a utility function to generate instances of a class
  function construct(constructor, args) {
    var c: any = function () {
      return constructor.apply(this, args);
    }
    c.prototype = constructor.prototype;
    return new c();
  }

  // the new constructor behaviour
  var f: any = function (...args) {
    console.log("New: " + original.name);
    return construct(original, args);
  }

  // copy prototype so intanceof operator still works
  f.prototype = original.prototype;

  // return new constructor (will override original)
  return f;
}

@logClass
class Person {

  public name: string;
  public surname: string;

  constructor(name: string, surname: string) {
    this.name = name;
    this.surname = surname;
  }
}
```

**Comment by darkobits** [comment]
Closing as stale. Please feel free to re-open at any time if the issue persists.
